### ISSUE TITLE
_initial()の追加提案

### ISSUE THREAD

**Issue by siromath** [takamoso/tatami#5]
cssのinitialキーワードのような動きをする`_initial()`ミックスイン(または関数)の追加提案です。

```scss
.box {
  @include _initial('width');
}

/*
コンパイル後:

.box {
  width: auto;
}
*/
```

ミックスインではなく関数にする場合は下記のようになると思います(引数を省略可能にできるのであればそちらが良いと思います)。

```scss
.box {
  width: _initial('width');
}
```

cssプロパティの数が多く実装に手間がかかると思いますが、これがあればIEでも使えるようになりますので、ご検討のほどよろしくお願いいたします。

**Comment by takamoso** [comment]
mixinで定義する形になると思います。
functionは以下のようなショートハンド記法の時にあると便利なので、併せて実装してみます。

```scss
.element {
  padding: 1em _initial('padding') 0;
}
```
